{
 "title": "Jira Sprint Board",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Board",
    "query": "SELECT id AS __value, name AS __text\nFROM boards\nWHERE\nid like ('%jira%')\n-- Below where clause must be used to get data from specific boards\n-- AND name IN ('board-name-1','board-name-2')\n"
   },
   {
    "name": "sprint_id",
    "label": "Sprint",
    "query": "SELECT\ns.id AS __value,\ns.name AS __text\nFROM\nboards AS b JOIN\nboard_sprints AS bs JOIN\nsprints AS s\nON\nb.id = bs.board_id AND\ns.id = bs.sprint_id\nWHERE b.id IN (${board_id})"
   },
   {
    "name": "type",
    "label": "Issue Type",
    "query": "REQUIREMENT,STORY,ENABLER,SPIKE,EPIC,SAGA,IMPROVEMENT,INITIATIVE,BUG,DEFECT,INCIDENT"
   }
  ]
 },
 "panels": [
  { "title": "1. Issue Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Issues [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "1. Total number of issues created.\n2. The requirements being calculated are filtered by \"requirement creation time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tcount(distinct(i.id))\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n\ti.original_status != 'cancelled'"
    }
   ]
  },
  {
   "title": "Number of Delivered Issue [Issues Created in Selected Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tcount(distinct(i.id))\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n\ti.status = 'DONE'\r\n    AND\r\n    i.original_status != 'cancelled'"
    }
   ]
  },
  {
   "title": "Issue Status Distribution over Sprint",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "dataset": "devlakeschema",
     "rawSql": "SELECT\r\n\tCOUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id END) AS number_of_delivered_issues,\r\n\tCOUNT(DISTINCT CASE WHEN i.status != 'DONE' THEN i.id END) AS number_of_open_issues,\r\n  sp.name AS sprint_name\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n    i.original_status != 'cancelled'\r\nGROUP BY sp.name"
    }
   ]
  },
  {
   "title": "Issue Delivery Rate [Issues Created in Selected Time Range]",
   "type": "stat",
   "description": "Issue Delivery Rate = count(Delivered Issues)/count(Issues)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    NOW() AS time,\r\n    (COUNT(DISTINCT(CASE WHEN i.status = 'Done' THEN i.id END))) / (COUNT(DISTINCT(i.id)))\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n\ti.original_status != 'cancelled'"
    }
   ]
  },
  {
   "title": "Issues Delivered Over Sprint In Percentage",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "dataset": "devlakeschema",
     "rawSql": "SELECT\r\n\t(COUNT(DISTINCT CASE WHEN i.status = 'DONE' THEN i.id END))/(COUNT(DISTINCT i.id))*100 AS issues_delivered_percentage,\r\n  sp.name AS sprint_name\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n  i.original_status != 'cancelled'\r\nGROUP BY sp.name"
    }
   ]
  },
  { "title": "2. Cycle Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Mean Cycle Time in Days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "devlake",
     "rawSql": "SELECT\n\tavg(cycle_lead_time_seconds/86400) AS value\nFROM (\n\tSELECT\n\t\tDISTINCT(issue_key) AS issue_key,\n\t\tMIN(issue_start_date) AS issue_start_date,\n\t\tMAX(issue_resolve_date) AS issue_resolve_date,\n\t\tTIMESTAMPDIFF(SECOND,MIN(issue_start_date),MAX(issue_resolve_date)) AS cycle_lead_time_seconds\n\t\t-- MIN(issue_key) AS issue_key\n\tFROM (\n\t\tSELECT\n\t\t\ti.id,\n\t\t\ti.issue_key,\n\t\t\t(CASE WHEN jci.to_string IN ('In Progress','Developing') THEN jc.created END) AS issue_start_date,\n\t\t\t(i.resolution_date) AS issue_resolve_date,\n\t\t\tjci.to_string AS to_string\n\t\tFROM\n\t\t\tissues i\n\t\tJOIN sprint_issues si ON si.issue_id = i.id\n\t\tJOIN sprints sp ON si.sprint_id = sp.id\n\t\tJOIN _tool_jira_issue_changelog_items jci on i._raw_data_id = jci._raw_data_id\n\t\tJOIN _tool_jira_issue_changelogs jc on jc.changelog_id = jci.changelog_id\n\t\tWHERE\n\t\t\t(i.original_type IN (${type}) or i.type IN (${type}))\n\t\t\tAND\n\t\t\tsp.id IN (${sprint_id})\n\t\t\tAND\n\t\t\ti.status = 'DONE'\n\t\t\tAND\n\t\t\ti.original_status != 'cancelled'\n\t--         AND\n\t\n\t\tORDER BY issue_start_date asc) issues_der\n\tWHERE \n\t\tto_string IN ('In Progress','Developing')\n\tGROUP BY issue_key\n) cycle_lead_time_der"
    }
   ]
  },
  {
   "title": "80% Issues' Cycle Time are less than # days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "devlake",
     "rawSql": "SELECT\n\tAVG(CASE WHEN _rank <= 0.8 THEN (cycle_lead_time_seconds/86400) END) AS value\nFROM (\n\tSELECT\n\t\tDISTINCT(issue_key) AS issue_key,\n\t\tMIN(issue_start_date) AS issue_start_date,\n\t\tMAX(issue_resolve_date) AS issue_resolve_date,\n\t\tTIMESTAMPDIFF(SECOND,MIN(issue_start_date),MAX(issue_resolve_date)) AS cycle_lead_time_seconds,\n    PERCENT_RANK() OVER (ORDER BY (TIMESTAMPDIFF(SECOND,MIN(issue_start_date),MAX(issue_resolve_date)))) AS _rank\n\tFROM (\n\t\tSELECT\n\t\t\ti.id,\n\t\t\ti.issue_key,\n\t\t\t(CASE WHEN jci.to_string IN ('In Progress','Developing') THEN jc.created END) AS issue_start_date,\n\t\t\t(i.resolution_date) AS issue_resolve_date,\n\t\t\tjci.to_string AS to_string\n\t\tFROM\n\t\t\tissues i\n\t\tJOIN sprint_issues si ON si.issue_id = i.id\n\t\tJOIN sprints sp ON si.sprint_id = sp.id\n\t\tJOIN _tool_jira_issue_changelog_items jci on i._raw_data_id = jci._raw_data_id\n\t\tJOIN _tool_jira_issue_changelogs jc on jc.changelog_id = jci.changelog_id\n\t\tWHERE\n\t\t\t(i.original_type IN (${type}) or i.type IN (${type}))\n\t\t\tAND\n\t\t\tsp.id IN (${sprint_id})\n\t\t\tAND\n\t\t\ti.status = 'DONE'\n\t\t\tAND\n\t\t\ti.original_status != 'cancelled'\n\t\tORDER BY issue_start_date asc) issues_der\n\tWHERE \n\t\tto_string IN ('In Progress','Developing')\n\tGROUP BY issue_key\n) cycle_lead_time_der"
    }
   ]
  },
  {
   "title": "Mean Cycle Time Over Sprint",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 14 },
   "targets": [
    {
     "dataset": "devlakeschema",
     "rawSql": "SELECT\r\n\tsprint_name,\r\n\tavg(cycle_lead_time_seconds/86400) AS mean_lead_time\r\nFROM (\r\n\tSELECT\r\n\t\tDISTINCT(issue_key) AS issue_key,\r\n\t\tMIN(issue_start_date) AS issue_start_date,\r\n\t\tMAX(issue_resolve_date) AS issue_resolve_date,\r\n\t\tTIMESTAMPDIFF(SECOND,MIN(issue_start_date),MAX(issue_resolve_date)) AS cycle_lead_time_seconds,\r\n\t\tMIN(sprint_name) AS sprint_name\r\n\t\t-- MIN(issue_key) AS issue_key\r\n\tFROM (\r\n\t\tSELECT\r\n\t\t\ti.id,\r\n\t\t\ti.issue_key,\r\n\t\t\t(CASE WHEN jci.to_string = 'In Progress' THEN jc.created END) AS issue_start_date,\r\n\t\t\t(i.resolution_date) AS issue_resolve_date,\r\n\t\t\tjci.to_string AS to_string,\r\n\t\t\tsp.name AS sprint_name\r\n\t\tFROM\r\n\t\t\tissues i\r\n\t\tJOIN sprint_issues si ON si.issue_id = i.id\r\n\t\tJOIN sprints sp ON si.sprint_id = sp.id\r\n\t\tJOIN _tool_jira_issue_changelog_items jci on i._raw_data_id = jci._raw_data_id\r\n\t\tJOIN _tool_jira_issue_changelogs jc on jc.changelog_id = jci.changelog_id\r\n\t\tWHERE\r\n\t\t\t(i.original_type IN (${type}) or i.type IN (${type}))\r\n\t\t\tAND\r\n\t\t\tsp.id IN (${sprint_id})\r\n\t\t\tAND\r\n\t\t\ti.status = 'DONE'\r\n\t\t\tAND\r\n\t\t\ti.original_status != 'cancelled'\r\n\t--         AND\r\n\t\r\n\t\tORDER BY issue_start_date asc) issues_der\r\n\tWHERE \r\n\t\tto_string IN ('In Progress')\r\n\tGROUP BY issue_key\r\n) cycle_lead_time_der\r\nGROUP BY sprint_name"
    }
   ]
  },
  { "title": "3. Issue Lead Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Mean Issue Lead Time in Days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    avg(lead_time_minutes)/1440 AS value\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n\ti.status = 'DONE'\r\n    AND\r\n    i.original_status != 'cancelled'"
    }
   ]
  },
  {
   "title": "80% Issues' Cycle Lead Time are less than # days [Issues Resolved in Select Time Range]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nAVG(CASE WHEN _rank <= 0.8 THEN lead_time_minutes END)/1440 AS value\r\nFROM (\r\n\tSELECT\r\n\t\tDISTINCT(issue_key),\r\n\t\tlead_time_minutes,\r\n\t\tPERCENT_RANK() OVER (ORDER BY lead_time_minutes) AS _rank\r\n\tFROM\r\n\t\tissues i\r\n\tJOIN\r\n\t\tsprint_issues si ON si.issue_id = i.id\r\n\tJOIN\t\r\n\t\tsprints sp ON si.sprint_id = sp.id\r\n\tWHERE\r\n\t\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\t\tAND\r\n\t\tsp.id IN (${sprint_id})\r\n\t\tAND\r\n\t\ti.status = 'DONE'\r\n\t\t\tAND\r\n\t\t\ti.original_status != 'cancelled'\r\n\t) mean_lead_time_der"
    }
   ]
  },
  {
   "title": "Mean Cycle Lead Time Over Sprint",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "dataset": "devlakeschema",
     "rawSql": "SELECT\r\n\t\tDISTINCT(sp.name) AS sprint_name,\r\n    avg(lead_time_minutes)/1440 AS mean_lead_time\r\nFROM\r\n\tissues i\r\nJOIN\r\n\tsprint_issues si ON si.issue_id = i.id\r\nJOIN\t\r\n\tsprints sp ON si.sprint_id = sp.id\r\nWHERE\r\n\t(i.original_type IN (${type}) OR i.type IN (${type}))\r\n\tAND\r\n\tsp.id IN (${sprint_id})\r\n\tAND\r\n\ti.status = 'DONE'\r\n    AND\r\n    i.original_status != 'cancelled'\r\nGROUP BY sprint_name"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   }
  }
 ]
}